/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/auth/register": {
    /** Register new user */
    post: {
      requestBody: {
        content: {
          "application/json": components["schemas"]["RegisterRequest"];
        };
      };
      responses: {
        /** @description User created */
        201: {
          content: {
            "application/json": components["schemas"]["RegisterResponse"];
          };
        };
        /** @description Bad request */
        400: {
          content: never;
        };
      };
    };
  };
  "/auth/login": {
    /** User login */
    post: {
      requestBody: {
        content: {
          "application/json": components["schemas"]["LoginRequest"];
        };
      };
      responses: {
        /** @description Login successful */
        200: {
          content: {
            "application/json": components["schemas"]["LoginResponse"];
          };
        };
        /** @description Unauthorized */
        401: {
          content: never;
        };
      };
    };
  };
  "/trips": {
    /** Create new trip */
    post: {
      requestBody: {
        content: {
          "application/json": components["schemas"]["CreateTripRequest"];
        };
      };
      responses: {
        /** @description Trip created */
        201: {
          content: {
            "application/json": components["schemas"]["CreateTripResponse"];
          };
        };
        /** @description Bad request */
        400: {
          content: never;
        };
      };
    };
  };
  "/trips/{id}": {
    /** Get trip details */
    get: {
      parameters: {
        path: {
          id: string;
        };
      };
      responses: {
        /** @description Trip details */
        200: {
          content: {
            "application/json": components["schemas"]["Trip"];
          };
        };
        /** @description Trip not found */
        404: {
          content: never;
        };
      };
    };
  };
  "/weather": {
    /** Get weather data */
    get: {
      parameters: {
        query: {
          lat: number;
          lon: number;
          from: string;
          to: string;
        };
      };
      responses: {
        /** @description Weather data */
        200: {
          content: {
            "application/json": components["schemas"]["WeatherResponse"];
          };
        };
        /** @description Bad request */
        400: {
          content: never;
        };
      };
    };
  };
  "/checklist/{tripId}": {
    /** Get trip checklist */
    get: {
      parameters: {
        path: {
          tripId: string;
        };
      };
      responses: {
        /** @description Checklist items */
        200: {
          content: {
            "application/json": components["schemas"]["ChecklistResponse"];
          };
        };
        /** @description Trip not found */
        404: {
          content: never;
        };
      };
    };
  };
  "/ai/ask": {
    /** Ask AI question */
    post: {
      requestBody: {
        content: {
          "application/json": components["schemas"]["AskRequest"];
        };
      };
      responses: {
        /** @description AI answer */
        200: {
          content: {
            "application/json": components["schemas"]["AskResponse"];
          };
        };
        /** @description Bad request */
        400: {
          content: never;
        };
      };
    };
  };
  "/health": {
    /** Health check */
    get: {
      responses: {
        /** @description Service health */
        200: {
          content: {
            "application/json": components["schemas"]["HealthResponse"];
          };
        };
      };
    };
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    RegisterRequest: {
      /** Format: email */
      email: string;
      password: string;
    };
    RegisterResponse: {
      userId?: string;
    };
    LoginRequest: {
      /** Format: email */
      email: string;
      password: string;
    };
    LoginResponse: {
      accessToken?: string;
    };
    Location: {
      /** Format: float */
      lat: number;
      /** Format: float */
      lon: number;
      name: string;
    };
    CreateTripRequest: {
      location: components["schemas"]["Location"];
      /** Format: date-time */
      startDate: string;
      /** Format: date-time */
      endDate: string;
      groupSize: number;
      /** @enum {string} */
      experience: "beginner" | "intermediate" | "advanced" | "expert";
      activities: string[];
    };
    CreateTripResponse: {
      id?: string;
    };
    Trip: {
      id?: string;
      location?: components["schemas"]["Location"];
      /** Format: date-time */
      startDate?: string;
      /** Format: date-time */
      endDate?: string;
      groupSize?: number;
      experience?: string;
      activities?: string[];
      /** Format: date-time */
      createdAt?: string;
      /** Format: date-time */
      updatedAt?: string;
    };
    WeatherResponse: {
      daily?: Record<string, never>[];
      alerts?: Record<string, never>[];
    };
    ChecklistItem: {
      name?: string;
      qty?: number;
      reason?: string;
      recommended?: boolean;
    };
    ChecklistResponse: {
      items?: components["schemas"]["ChecklistItem"][];
    };
    AskRequest: {
      question: string;
      tripId?: string;
      /** @default false */
      stream?: boolean;
    };
    Citation: {
      title?: string;
      url?: string;
      /** Format: float */
      score?: number;
    };
    AskResponse: {
      answer?: string;
      citations?: components["schemas"]["Citation"][];
    };
    HealthResponse: {
      status?: string;
      service?: string;
      version?: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export type operations = Record<string, never>;
