/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/ingest/url": {
    /** Ingest URL content */
    post: {
      requestBody: {
        content: {
          "application/json": components["schemas"]["IngestUrlRequest"];
        };
      };
      responses: {
        /** @description URL ingestion accepted */
        202: {
          content: {
            "application/json": components["schemas"]["IngestUrlResponse"];
          };
        };
        /** @description Bad request */
        400: {
          content: never;
        };
      };
    };
  };
  "/search": {
    /** Search documents */
    post: {
      requestBody: {
        content: {
          "application/json": components["schemas"]["SearchRequest"];
        };
      };
      responses: {
        /** @description Search results */
        200: {
          content: {
            "application/json": components["schemas"]["SearchResponse"];
          };
        };
        /** @description Bad request */
        400: {
          content: never;
        };
      };
    };
  };
  "/answer": {
    /** Get AI answer */
    post: {
      requestBody: {
        content: {
          "application/json": components["schemas"]["AnswerRequest"];
        };
      };
      responses: {
        /** @description AI answer */
        200: {
          content: {
            "application/json": components["schemas"]["AnswerResponse"];
          };
        };
        /** @description Bad request */
        400: {
          content: never;
        };
      };
    };
  };
  "/answer/stream": {
    /** Stream AI answer */
    post: {
      requestBody: {
        content: {
          "application/json": components["schemas"]["AnswerRequest"];
        };
      };
      responses: {
        /** @description Streamed answer */
        200: {
          content: {
            "text/event-stream": string;
          };
        };
      };
    };
  };
  "/health": {
    /** Health check */
    get: {
      responses: {
        /** @description Service health */
        200: {
          content: {
            "application/json": components["schemas"]["HealthResponse"];
          };
        };
      };
    };
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    IngestUrlRequest: {
      /** Format: uri */
      url: string;
    };
    IngestUrlResponse: {
      accepted?: boolean;
    };
    SearchRequest: {
      query: string;
      /** @default 10 */
      topK?: number;
    };
    SearchResult: {
      text?: string;
      url?: string;
      title?: string;
      /** Format: float */
      score?: number;
    };
    SearchResponse: {
      results?: components["schemas"]["SearchResult"][];
    };
    AnswerRequest: {
      question: string;
      tripContext?: Record<string, never>;
      weather?: Record<string, never>;
    };
    Citation: {
      title?: string;
      url?: string;
      /** Format: float */
      score?: number;
    };
    AnswerResponse: {
      answer?: string;
      citations?: components["schemas"]["Citation"][];
    };
    HealthResponse: {
      ok?: boolean;
      service?: string;
      version?: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export type operations = Record<string, never>;
