version: '3.8'

services:
  frontend:
    build:
      context: ..
      dockerfile: docker/frontend/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - PORT=3000

  api:
    build:
      context: ..
      dockerfile: docker/api/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - MONGO_URI=mongodb://mongo:27017/trailwise
      - JWT_SECRET=dev_change_me
      - OPENWEATHER_API_KEY=c5df017a7961da45a250532bba658b24
    depends_on:
      - mongo

  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  rag:
    build:
      context: ..
      dockerfile: docker/rag/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - RAG_VERSION=0.0.1
  
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin

volumes:
  mongo_data:

